#!/bin/bash
# Export YouTube cookies from your browser

echo "========================================="
echo "Export YouTube Cookies"
echo "========================================="
echo ""
echo "We need fresh YouTube cookies to bypass bot detection."
echo ""
echo "Option 1: Use yt-dlp to extract from browser (Recommended)"
echo "----------------------------------------"
echo "Run this command:"
echo ""
echo "  yt-dlp --cookies-from-browser chrome --cookies youtube-cookies.txt --skip-download 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'"
echo ""
echo "Or for Safari:"
echo "  yt-dlp --cookies-from-browser safari --cookies youtube-cookies.txt --skip-download 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'"
echo ""
echo "Or for Firefox:"
echo "  yt-dlp --cookies-from-browser firefox --cookies youtube-cookies.txt --skip-download 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'"
echo ""
echo "----------------------------------------"
echo ""
echo "Option 2: Use browser extension"
echo "----------------------------------------"
echo "1. Install 'Get cookies.txt LOCALLY' extension"
echo "   Chrome: https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc"
echo "   Firefox: https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/"
echo ""
echo "2. Go to https://www.youtube.com"
echo "3. Make sure you're logged in"
echo "4. Click the extension icon"
echo "5. Click 'Export' or 'Download'"
echo "6. Save as youtube-cookies.txt"
echo ""
echo "----------------------------------------"
echo ""
echo "After exporting, upload to S3:"
echo ""
echo "  export AWS_PROFILE=production"
echo "  aws s3 cp youtube-cookies.txt s3://music-transcription-audio-test-090130568474/config/youtube-cookies.txt --region us-east-1"
echo ""
echo "Then test again:"
echo "  cd simple-pipeline"
echo "  ./test.sh 'https://www.youtube.com/watch?v=Q-RKhgsZu64'"
echo ""
echo "========================================="
