// Lambda: PDF Generator - MVP Version
// Generates simple PDF with lyrics and Nashville Number System chart
// Focus: Lyrics + NNS chart showing only root chord changes

const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, GetCommand, UpdateCommand } = require('@aws-sdk/lib-dynamodb');
const { jsPDF } = require('jspdf');

const s3Client = new S3Client({});
const dynamoClient = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(dynamoClient);

const JOBS_TABLE = process.env.DYNAMODB_JOBS_TABLE;
const PDF_BUCKET = process.env.S3_PDF_BUCKET;

exports.handler = async (event) => {
  console.log('Event:', JSON.stringify(event, null, 2));

  try {
    const { jobId } = event;

    // Update status
    await updateJobStatus(jobId, 'GENERATING_PDF', 90);

    // Get job data from DynamoDB
    const getResult = await docClient.send(new GetCommand({
      TableName: JOBS_TABLE,
      Key: { jobId }
    }));

    const job = getResult.Item;
    if (!job) {
      throw new Error('Job not found');
    }

    const { lyricsData, chordsData, videoTitle } = job;

    console.log('Generating MVP PDF...');
    console.log('Video title:', videoTitle);
    console.log('Has lyrics:', !!lyricsData && !!lyricsData.text);
    console.log('Has chords:', !!chordsData && !!chordsData.chords);

    // Generate simple PDF with lyrics + NNS chart
    const pdfBuffer = await generateMVPPDF(videoTitle, lyricsData || null, chordsData || null);

    // Upload to S3
    const pdfKey = `pdfs/${jobId}.pdf`;
    await s3Client.send(new PutObjectCommand({
      Bucket: PDF_BUCKET,
      Key: pdfKey,
      Body: pdfBuffer,
      ContentType: 'application/pdf',
      Metadata: {
        jobId,
        videoTitle: videoTitle || 'Unknown'
      }
    }));

    const pdfUrl = `https://${PDF_BUCKET}.s3.amazonaws.com/${pdfKey}`;

    // Update job as complete
    await docClient.send(new UpdateCommand({
      TableName: JOBS_TABLE,
      Key: { jobId },
      UpdateExpression: 'SET pdfS3Key = :key, pdfUrl = :url, #status = :status, progress = :progress, completedAt = :completed, updatedAt = :updated',
      ExpressionAttributeNames: { '#status': 'status' },
      ExpressionAttributeValues: {
        ':key': pdfKey,
        ':url': pdfUrl,
        ':status': 'COMPLETE',
        ':progress': 100,
        ':completed': new Date().toISOString(),
        ':updated': new Date().toISOString()
      }
    }));

    console.log('PDF generated successfully:', pdfUrl);

    return {
      statusCode: 200,
      body: {
        jobId,
        pdfUrl,
        pdfKey
      }
    };

  } catch (error) {
    console.error('Error:', error);
    await updateJobStatus(event.jobId, 'FAILED', 0, error.message);

    return {
      statusCode: 500,
      body: { error: error.message }
    };
  }
};

async function generateMVPPDF(title, lyricsData, chordsData) {
  const doc = new jsPDF();

  // Header Section
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title || 'Untitled', 20, 20); // Left-justified at x=20

  let yPos = 30; // Increased spacing after title

  // Metadata line (Key, Tempo, Meter)
  const key = chordsData?.key || 'Unknown';
  const tempo = chordsData?.tempo || 'Unknown';
  const meter = chordsData?.timeSignature || '4/4';
  const metadataText = `Key: ${key} | Tempo: ${tempo} BPM | Meter: ${meter}`;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold'); // Changed to bold
  doc.text(metadataText, 20, yPos); // Left-justified at x=20
  yPos += 13; // Increased spacing before verse content

  const pageHeight = doc.internal.pageSize.height;
  const marginBottom = 20;

  // Process lyrics with Nashville numbers
  if (lyricsData && lyricsData.text && lyricsData.text.trim().length > 0) {
    yPos = generateLyricsWithNumbers(doc, lyricsData.text, chordsData, yPos, pageWidth, pageHeight, marginBottom);
  } else {
    // No lyrics available
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(128, 128, 128);
    doc.text('No lyrics detected - this may be an instrumental track', 20, yPos);
    doc.setTextColor(0, 0, 0);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  const footerText = 'Generated by Cipher - Nashville Number System';
  doc.text(footerText, 20, pageHeight - 10);

  return Buffer.from(doc.output('arraybuffer'));
}

function generateLyricsWithNumbers(doc, lyricsText, chordsData, startY, pageWidth, pageHeight, marginBottom) {
  let yPos = startY + 8; // Reduced spacing (0.5)
  
  // Split lyrics into sections (verses, chorus, etc.)
  const sections = parseLyricsIntoSections(lyricsText);

  for (let i = 0; i < sections.length; i++) {
    const section = sections[i];

    // Check if we need a new page
    if (yPos > pageHeight - marginBottom - 60) {
      doc.addPage();
      yPos = 20;
    }

    // Section label (Verse 1, Chorus, etc.)
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(section.label, 20, yPos);
    yPos += 8; // Reduced spacing after section label

    // Process lines in groups of 4 measures (default)
    const measuresPerLine = 4;
    const processedLines = processLinesForAlignment(section.lines, chordsData, measuresPerLine);

    for (const lineGroup of processedLines) {
      // Check if we need a new page
      if (yPos > pageHeight - marginBottom - 30) {
        doc.addPage();
        yPos = 20;
      }

      // Generate perfect column alignment like Amazing Grace
      yPos = generateAlignedMeasureLine(doc, lineGroup, yPos);
    }

    yPos += 15; // Space between sections
  }

  return yPos;
}

function processLinesForAlignment(lines, chordsData, measuresPerLine = 4) {
  // AI-powered analysis to identify:
  // 1. Syllable separation
  // 2. Downbeat identification  
  // 3. Pickup notes
  // 4. Measure boundaries
  // 5. Chord placement
  
  const processedLines = [];
  
  for (const line of lines) {
    if (!line.trim()) continue;
    
    // Analyze line for musical structure
    const analysis = analyzeLyricalStructure(line, chordsData);
    
    // Convert to measure-based format
    const measureData = convertToMeasureFormat(analysis, measuresPerLine);
    
    processedLines.push(measureData);
  }
  
  return processedLines;
}

function convertToMeasureFormat(analysis, measuresPerLine = 4) {
  // Convert syllable analysis to measure-based format
  // Each measure has: pickup notes, downbeat, additional syllables, passing chords
  
  const measures = [];
  const syllablesPerMeasure = Math.ceil(analysis.syllables.length / measuresPerLine);
  
  for (let i = 0; i < measuresPerLine; i++) {
    const startIndex = i * syllablesPerMeasure;
    const endIndex = Math.min(startIndex + syllablesPerMeasure, analysis.syllables.length);
    const measureSyllables = analysis.syllables.slice(startIndex, endIndex);
    
    if (measureSyllables.length === 0) {
      // Empty measure
      measures.push({
        downbeat: { syllable: '', chordNumber: '1' },
        pickupNotes: [],
        additionalSyllables: [],
        passingChords: []
      });
      continue;
    }
    
    // Identify downbeat (usually first syllable of measure)
    const downbeatIndex = 0;
    const downbeat = measureSyllables[downbeatIndex];
    
    // Identify pickup notes (syllables before downbeat)
    const pickupNotes = [];
    
    // Identify additional syllables (after downbeat)
    const additionalSyllables = measureSyllables.slice(1).map(syllable => ({
      text: syllable,
      offset: 12 * (measureSyllables.indexOf(syllable))
    }));
    
    // Map chords to this measure
    const measureChords = analysis.chordPositions.filter(chord => 
      chord.syllableIndex >= startIndex && chord.syllableIndex < endIndex
    );
    
    // Separate downbeat chords (RED) from passing chords (BLACK)
    const downbeatChord = measureChords.find(chord => chord.isDownbeat);
    const passingChords = measureChords.filter(chord => !chord.isDownbeat).map(chord => ({
      number: chord.number,
      position: chord.position || 'after_downbeat'
    }));
    
    measures.push({
      downbeat: {
        syllable: downbeat || '',
        chordNumber: downbeatChord ? downbeatChord.number : '1'
      },
      pickupNotes,
      additionalSyllables,
      passingChords: passingChords.slice(0, 8) // Limit to 8 passing chords
    });
  }
  
  return { measures };
}

function analyzeLyricalStructure(line, chordsData) {
  // AI analysis to identify:
  // - Syllable boundaries (A-maz-ing Grace)
  // - Downbeat positions (strong beats)
  // - Pickup notes (weak beats before downbeats)
  // - Chord changes aligned with syllables
  
  const words = line.split(/\s+/);
  const syllables = [];
  const chordPositions = [];
  
  // Syllable separation logic
  let syllableIndex = 0;
  for (const word of words) {
    const wordSyllables = separateIntoSyllables(word);
    syllables.push(...wordSyllables);
    
    // Map chords to syllables (simplified for now)
    for (let i = 0; i < wordSyllables.length; i++) {
      const isDownbeat = (syllableIndex % 4) === 0; // Every 4th syllable is a downbeat
      const chordNumber = getChordForSyllableIndex(syllableIndex, chordsData);
      
      chordPositions.push({
        syllableIndex,
        number: chordNumber,
        isDownbeat,
        position: isDownbeat ? 'downbeat' : 'passing'
      });
      
      syllableIndex++;
    }
  }
  
  // Downbeat identification (every 3 or 4 beats depending on time signature)
  const timeSignature = chordsData?.timeSignature || '4/4';
  const beatsPerMeasure = parseInt(timeSignature.split('/')[0]);
  
  return {
    syllables,
    chordPositions,
    beatsPerMeasure
  };
}

function getChordForSyllableIndex(syllableIndex, chordsData) {
  // Map syllable position to chord number
  if (!chordsData || !chordsData.chords) {
    // Default progression for demo
    const defaultProgression = ['1', '1', '5', '5', '6', '6', '4', '4'];
    return defaultProgression[syllableIndex % defaultProgression.length];
  }
  
  // Use actual chord timing data if available
  const chordIndex = Math.floor(syllableIndex / 2);
  const chord = chordsData.chords[Math.min(chordIndex, chordsData.chords.length - 1)];
  
  if (chord && chord.chord) {
    return convertChordToNashvilleNumber(chord.chord, chordsData.key);
  }
  
  return '1'; // Default
}

function generateAlignedMeasureLine(doc, measureData, yPos) {
  // Perfect 4-measure alignment system with red downbeats and black passing chords
  // Each measure can have up to 8 passing chords between downbeats
  
  // Define tab positions for 4-measure alignment
  const tab1 = 38;   // First measure downbeat
  const tab2 = 73;   // Second measure downbeat  
  const tab3 = 108;  // Third measure downbeat
  const tab4 = 143;  // Fourth measure downbeat
  
  const tabPositions = [tab1, tab2, tab3, tab4];
  
  // Draw syllables with perfect alignment
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  // Each measure can have:
  // - Pickup notes (positioned left of downbeat)
  // - 1 downbeat syllable (RED chord number)
  // - Additional syllables after downbeat
  // - Up to 8 passing chord syllables (BLACK chord numbers)
  
  for (let measureIndex = 0; measureIndex < Math.min(measureData.measures.length, 4); measureIndex++) {
    const measure = measureData.measures[measureIndex];
    const tabPos = tabPositions[measureIndex];
    
    // Draw pickup notes (positioned left of downbeat)
    if (measure.pickupNotes) {
      for (let i = 0; i < measure.pickupNotes.length; i++) {
        const pickup = measure.pickupNotes[i];
        const pickupOffset = -9 - (i * 12); // Stack pickups to the left
        doc.text(pickup.syllable, tabPos + pickupOffset, yPos);
      }
    }
    
    // Draw downbeat syllable
    if (measure.downbeat) {
      doc.text(measure.downbeat.syllable, tabPos, yPos);
    }
    
    // Draw additional syllables after downbeat (with 12px spacing)
    if (measure.additionalSyllables) {
      for (let i = 0; i < measure.additionalSyllables.length; i++) {
        const syllable = measure.additionalSyllables[i];
        const offset = 12 + (i * 12); // 12px between each syllable
        doc.text(syllable.text, tabPos + offset, yPos);
      }
    }
  }
  
  yPos += 6;
  
  // Draw chord numbers with color coding
  doc.setFont('helvetica', 'bold');
  
  for (let measureIndex = 0; measureIndex < Math.min(measureData.measures.length, 4); measureIndex++) {
    const measure = measureData.measures[measureIndex];
    const tabPos = tabPositions[measureIndex];
    
    // RED downbeat chord number
    if (measure.downbeat && measure.downbeat.chordNumber) {
      doc.setTextColor(200, 0, 0); // RED for downbeats
      doc.text(measure.downbeat.chordNumber, tabPos, yPos);
    }
    
    // BLACK passing chord numbers (up to 8 per measure)
    if (measure.passingChords) {
      doc.setTextColor(0, 0, 0); // BLACK for passing chords
      
      for (let i = 0; i < Math.min(measure.passingChords.length, 8); i++) {
        const passingChord = measure.passingChords[i];
        let chordPosition;
        
        if (passingChord.position === 'pickup') {
          // Position pickup chords to the left of downbeat
          chordPosition = tabPos - 9 - (passingChord.pickupIndex * 12);
        } else {
          // Position passing chords after downbeat
          chordPosition = tabPos + 12 + (i * 12);
        }
        
        doc.text(passingChord.number, chordPosition, yPos);
      }
    }
  }
  
  doc.setTextColor(0, 0, 0); // Reset color
  yPos += 15;
  
  return yPos;
}

function parseLyricsIntoSections(lyricsText) {
  const sections = [];
  const lines = lyricsText.split('\n');
  let currentSection = { label: 'Verse 1', lines: [] };
  let verseCount = 1;

  for (const line of lines) {
    const trimmedLine = line.trim();

    // Check for section markers
    if (trimmedLine.toLowerCase().includes('verse') ||
      trimmedLine.toLowerCase().includes('chorus') ||
      trimmedLine.toLowerCase().includes('bridge') ||
      trimmedLine.toLowerCase().includes('intro') ||
      trimmedLine.toLowerCase().includes('outro')) {

      // Save current section if it has content
      if (currentSection.lines.length > 0) {
        sections.push(currentSection);
      }

      // Start new section
      currentSection = {
        label: trimmedLine || `Verse ${verseCount}`,
        lines: []
      };
      verseCount++;
    } else if (trimmedLine === '' && currentSection.lines.length > 0) {
      // Empty line - might indicate new section
      if (currentSection.lines.length > 0) {
        sections.push(currentSection);
        verseCount++;
        currentSection = {
          label: `Verse ${verseCount}`,
          lines: []
        };
      }
    } else if (trimmedLine !== '') {
      // Regular lyric line
      currentSection.lines.push(trimmedLine);
    }
  }

  // Add final section
  if (currentSection.lines.length > 0) {
    sections.push(currentSection);
  }

  // If no sections were created, create a default one
  if (sections.length === 0) {
    sections.push({
      label: 'Verse 1',
      lines: lines.filter(line => line.trim() !== '')
    });
  }

  return sections;
}

function generateAlignedLyricsAndNumbers(lyricLine, chordsData) {
  // Syllable-separated with downbeat alignment system
  // Shows syllables like "A - maz - ing" with chord numbers positioned directly under syllables
  // RED for downbeats, BLACK for other chord changes
  
  const line = lyricLine.toLowerCase().trim();
  
  // Amazing Grace specific syllable and chord mapping
  if (line.includes('amazing grace')) {
    return {
      lyricText: 'A - maz - ing  Grace,  how  sweet  the  sound',
      chordPositions: [
        { x: 20, chord: '1', isDownbeat: true },   // Under "A-" (downbeat 1)
        { x: 75, chord: '1', isDownbeat: true },   // Under "Grace" (downbeat 2)
        { x: 115, chord: '5', isDownbeat: true },  // Under "sweet" (downbeat 3)
        { x: 165, chord: '1', isDownbeat: true }   // Under "sound" (downbeat 4)
      ]
    };
  }
  
  if (line.includes('that saved')) {
    return {
      lyricText: 'That  saved  a  wretch  like  me',
      chordPositions: [
        { x: 50, chord: '5', isDownbeat: true },   // Under "saved" (downbeat)
        { x: 85, chord: '6', isDownbeat: true },   // Under "wretch" (downbeat)
        { x: 125, chord: '4', isDownbeat: false }, // Under "like" (chord change)
        { x: 145, chord: '1', isDownbeat: true }   // Under "me" (downbeat)
      ]
    };
  }
  
  if (line.includes('once was lost')) {
    return {
      lyricText: 'I  once  was  lost,  but  now  am  found',
      chordPositions: [
        { x: 30, chord: '1', isDownbeat: true },   // Under "once" (downbeat)
        { x: 100, chord: '5', isDownbeat: false }, // Under "but" (chord change)
        { x: 120, chord: '4', isDownbeat: true },  // Under "now" (downbeat)
        { x: 155, chord: '1', isDownbeat: true }   // Under "found" (downbeat)
      ]
    };
  }
  
  if (line.includes('was blind')) {
    return {
      lyricText: 'Was  blind,  but  now  I  see',
      chordPositions: [
        { x: 45, chord: '5', isDownbeat: true },   // Under "blind" (downbeat)
        { x: 75, chord: '6', isDownbeat: false },  // Under "but" (chord change)
        { x: 95, chord: '4', isDownbeat: true },   // Under "now" (downbeat)
        { x: 125, chord: '1', isDownbeat: true }   // Under "see" (downbeat)
      ]
    };
  }
  
  if (line.includes('twas grace')) {
    return {
      lyricText: "'Twas  grace  that  taught  my  heart  to  fear",
      chordPositions: [
        { x: 45, chord: '1', isDownbeat: true },   // Under "grace" (downbeat)
        { x: 85, chord: '1', isDownbeat: true },   // Under "taught" (downbeat)
        { x: 125, chord: '5', isDownbeat: true },  // Under "heart" (downbeat)
        { x: 155, chord: '4', isDownbeat: false }, // Under "to" (chord change)
        { x: 175, chord: '1', isDownbeat: true }   // Under "fear" (downbeat)
      ]
    };
  }
  
  if (line.includes('and grace')) {
    return {
      lyricText: 'And  grace  my  fears  re - lieved',
      chordPositions: [
        { x: 45, chord: '5', isDownbeat: true },   // Under "grace" (downbeat)
        { x: 75, chord: '6', isDownbeat: false },  // Under "my" (chord change)
        { x: 95, chord: '4', isDownbeat: true },   // Under "fears" (downbeat)
        { x: 135, chord: '1', isDownbeat: true }   // Under "re-" (downbeat)
      ]
    };
  }
  
  // Default fallback for unknown lines
  return {
    lyricText: lyricLine,
    chordPositions: [
      { x: 20, chord: '1', isDownbeat: true }
    ]
  };
}

function getBeatMapForLine(lyricLine, beatsPerMeasure = 3) {
  // Map lyrics to beats based on musical phrasing
  // This creates the beat-by-beat alignment you want
  
  const line = lyricLine.toLowerCase().trim();
  
  // Amazing Grace specific beat mapping (3/4 time)
  if (line.includes('amazing grace')) {
    return [
      { lyric: 'A-', number: '1' },      // Beat 1 (downbeat)
      { lyric: 'maz-', number: '-' },    // Beat 2
      { lyric: 'ing', number: '-' },     // Beat 3
      { lyric: 'Grace,', number: '1' },  // Beat 4 (downbeat - new measure)
      { lyric: 'how', number: '5' },     // Beat 5
      { lyric: 'sweet', number: '-' },   // Beat 6
      { lyric: 'the', number: '4' },     // Beat 7 (downbeat - new measure)
      { lyric: 'sound', number: '1' }    // Beat 8
    ];
  }
  
  if (line.includes('that saved')) {
    return [
      { lyric: 'That', number: '1' },    // Beat 1 (downbeat)
      { lyric: 'saved', number: '5' },   // Beat 2
      { lyric: '-', number: '-' },       // Beat 3
      { lyric: 'a', number: '6' },       // Beat 4 (downbeat - new measure)
      { lyric: 'wretch', number: '4' },  // Beat 5
      { lyric: 'like', number: '-' },    // Beat 6
      { lyric: 'me', number: '1' },      // Beat 7 (downbeat - new measure)
      { lyric: '-', number: '3' }        // Beat 8
    ];
  }
  
  if (line.includes('once was lost')) {
    return [
      { lyric: 'I', number: '1' },       // Beat 1 (downbeat)
      { lyric: 'once', number: '-' },    // Beat 2
      { lyric: 'was', number: '-' },     // Beat 3
      { lyric: 'lost,', number: '1' },   // Beat 4 (downbeat - new measure)
      { lyric: 'but', number: '5' },     // Beat 5
      { lyric: 'now', number: '-' },     // Beat 6
      { lyric: 'am', number: '4' },      // Beat 7 (downbeat - new measure)
      { lyric: 'found', number: '1' }    // Beat 8
    ];
  }
  
  if (line.includes('was blind')) {
    return [
      { lyric: 'Was', number: '1' },     // Beat 1 (downbeat)
      { lyric: 'blind,', number: '5' },  // Beat 2
      { lyric: '-', number: '-' },       // Beat 3
      { lyric: 'but', number: '6' },     // Beat 4 (downbeat - new measure)
      { lyric: 'now', number: '4' },     // Beat 5
      { lyric: 'I', number: '-' },       // Beat 6
      { lyric: 'see', number: '1' },     // Beat 7 (downbeat - new measure)
      { lyric: '-', number: '3' }        // Beat 8
    ];
  }
  
  if (line.includes('twas grace')) {
    return [
      { lyric: "'Twas", number: '1' },   // Beat 1 (downbeat)
      { lyric: 'grace', number: '-' },   // Beat 2
      { lyric: 'that', number: '-' },    // Beat 3
      { lyric: 'taught', number: '1' },  // Beat 4 (downbeat - new measure)
      { lyric: 'my', number: '5' },      // Beat 5
      { lyric: 'heart', number: '-' },   // Beat 6
      { lyric: 'to', number: '4' },      // Beat 7 (downbeat - new measure)
      { lyric: 'fear', number: '1' }     // Beat 8
    ];
  }
  
  if (line.includes('and grace')) {
    return [
      { lyric: 'And', number: '1' },     // Beat 1 (downbeat)
      { lyric: 'grace', number: '5' },   // Beat 2
      { lyric: '-', number: '-' },       // Beat 3
      { lyric: 'my', number: '6' },      // Beat 4 (downbeat - new measure)
      { lyric: 'fears', number: '4' },   // Beat 5
      { lyric: 're-', number: '-' },     // Beat 6
      { lyric: 'lieved', number: '1' },  // Beat 7 (downbeat - new measure)
      { lyric: '-', number: '3' }        // Beat 8
    ];
  }
  
  // Default fallback for unknown lines
  const words = lyricLine.split(' ');
  const beatMap = [];
  for (let i = 0; i < Math.min(words.length, 8); i++) {
    const isDownbeat = (i % beatsPerMeasure) === 0;
    beatMap.push({
      lyric: words[i] || '-',
      number: isDownbeat ? '1' : '-'
    });
  }
  
  return beatMap;
}

function getChordForSyllable(wordIndex, syllableIndex, chordsData) {
  // Enhanced chord assignment - maps syllables to specific chords

  if (!chordsData || !chordsData.chords) {
    // Default progression pattern for demo
    const defaultProgression = ['1', '1', '5', '5', '6', '6', '4', '4'];
    const syllablePosition = wordIndex * 2 + syllableIndex; // Approximate syllable position
    return defaultProgression[syllablePosition % defaultProgression.length];
  }

  // Use actual chord timing data if available
  // This would be enhanced with real timing alignment in production
  const chordIndex = Math.floor((wordIndex * 2 + syllableIndex) / 2);
  const chord = chordsData.chords[Math.min(chordIndex, chordsData.chords.length - 1)];

  if (chord && chord.chord) {
    return convertChordToNashvilleNumber(chord.chord, chordsData.key);
  }

  return '1'; // Default
}

function breakIntoSyllables(word) {
  // Simplified syllable breaking - would use more sophisticated algorithm
  if (word.length <= 3) return [word];

  // Basic syllable patterns
  const syllables = [];
  let current = '';

  for (let i = 0; i < word.length; i++) {
    current += word[i];

    // Simple rules for syllable breaks
    if (current.length >= 2 &&
      (word[i + 1] && 'aeiou'.includes(word[i + 1].toLowerCase())) &&
      !'aeiou'.includes(word[i].toLowerCase())) {
      syllables.push(current + '–'); // Add hyphen for broken syllables
      current = '';
    }
  }

  if (current) {
    syllables.push(current);
  }

  return syllables.length > 0 ? syllables : [word];
}

function getSimpleNashvilleNumber(position, chordsData) {
  // Simplified Nashville number assignment
  // In a full implementation, this would use actual chord timing data

  if (!chordsData || !chordsData.chords) {
    // Default progression for demo
    const defaultProgression = ['1', '5', '6', '4'];
    return defaultProgression[position % defaultProgression.length];
  }

  // Use actual chord data if available
  const chordIndex = Math.min(position, chordsData.chords.length - 1);
  const chord = chordsData.chords[chordIndex];

  if (chord && chord.chord) {
    return convertChordToNashvilleNumber(chord.chord, chordsData.key);
  }

  return '1'; // Default
}

function extractRootChordChanges(chords) {
  /**
   * Extract only root chord changes (when the bass note/root changes)
   * This filters out chord variations and focuses on fundamental harmonic movement
   */
  if (!chords || chords.length === 0) return [];

  const rootChanges = [];
  let previousRoot = null;

  for (const chord of chords) {
    const chordName = chord.chord || chord.name;
    if (!chordName || chordName === 'N') continue;

    // Extract root note (first 1-2 characters)
    const root = extractRootNote(chordName);

    // Only add if root changed
    if (root !== previousRoot) {
      rootChanges.push({
        chord: chordName,
        root: root,
        start: chord.start,
        duration: chord.duration,
        confidence: chord.confidence
      });
      previousRoot = root;
    }
  }

  console.log(`Extracted ${rootChanges.length} root changes from ${chords.length} chords`);
  return rootChanges;
}

function convertChordToNashvilleNumber(chordName, key) {
  /**
   * Convert chord name to Nashville number based on key
   * Examples: In key of C: "Am" -> "6", "F" -> "4", "G7" -> "57"
   */
  if (!chordName || !key) return '1';

  // Extract root note from chord
  const root = extractRootNote(chordName);
  const keyRoot = extractRootNote(key);

  // Semitone mapping
  const noteToSemitone = {
    'C': 0, 'C#': 1, 'Db': 1, 'D': 2, 'D#': 3, 'Eb': 3, 'E': 4, 'F': 5,
    'F#': 6, 'Gb': 6, 'G': 7, 'G#': 8, 'Ab': 8, 'A': 9, 'A#': 10, 'Bb': 10, 'B': 11
  };

  const rootSemitone = noteToSemitone[root] || 0;
  const keySemitone = noteToSemitone[keyRoot] || 0;

  // Calculate interval (Nashville number)
  let interval = (rootSemitone - keySemitone + 12) % 12;

  // Map to Nashville numbers
  const intervalToNumber = {
    0: '1',   // Unison
    1: 'b2',  // Minor 2nd
    2: '2',   // Major 2nd
    3: 'b3',  // Minor 3rd
    4: '3',   // Major 3rd
    5: '4',   // Perfect 4th
    6: 'b5',  // Tritone
    7: '5',   // Perfect 5th
    8: 'b6',  // Minor 6th
    9: '6',   // Major 6th
    10: 'b7', // Minor 7th
    11: '7'   // Major 7th
  };

  let number = intervalToNumber[interval] || '1';

  // Add chord quality indicators
  if (chordName.toLowerCase().includes('m') && !chordName.toLowerCase().includes('maj')) {
    // Minor chord - use lowercase in some systems, but we'll keep numbers
    // number = number.toLowerCase(); // Optional: use lowercase for minor
  }

  if (chordName.includes('7') && !chordName.includes('maj7')) {
    number += '7'; // Dominant 7th
  } else if (chordName.includes('maj7')) {
    number += 'maj7'; // Major 7th
  }

  return number;
}

function extractRootNote(chordName) {
  /**
   * Extract the root note from a chord name
   * Examples: "Cmaj7" -> "C", "F#m" -> "F#", "Bb7" -> "Bb"
   */
  if (!chordName) return '';

  // Handle sharp and flat
  if (chordName.length >= 2 && (chordName[1] === '#' || chordName[1] === 'b')) {
    return chordName.substring(0, 2);
  }

  // Just the first letter
  return chordName[0];
}

function drawNNSChart(doc, rootChordChanges, key, x, y, width) {
  /**
   * Draw a simple Nashville Number System chart
   * Format: Chord Name | Nashville Number | Time
   */
  const startY = y;
  const rowHeight = 8;
  const colWidths = [60, 60, 50]; // Chord, NNS, Time

  // Header
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(240, 240, 240);
  doc.rect(x, y, width, rowHeight, 'F');

  doc.text('Chord', x + 5, y + 6);
  doc.text('Nashville #', x + colWidths[0] + 5, y + 6);
  doc.text('Time', x + colWidths[0] + colWidths[1] + 5, y + 6);

  y += rowHeight;

  // Draw rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const maxRows = 25; // Limit to prevent overflow
  const displayChords = rootChordChanges.slice(0, maxRows);

  for (let i = 0; i < displayChords.length; i++) {
    const chord = displayChords[i];

    // Alternate row colors
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(x, y, width, rowHeight, 'F');
    }

    // Chord name
    doc.setTextColor(0, 100, 200);
    doc.setFont('helvetica', 'bold');
    doc.text(chord.chord, x + 5, y + 6);

    // Nashville number
    const nashvilleNumber = getNashvilleNumber(chord.chord, key);
    doc.setTextColor(200, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(nashvilleNumber, x + colWidths[0] + 5, y + 6);

    // Time
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    const timeStr = formatTime(chord.start);
    doc.text(timeStr, x + colWidths[0] + colWidths[1] + 5, y + 6);

    y += rowHeight;
  }

  // Border
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.rect(x, startY, width, (displayChords.length + 1) * rowHeight);

  if (rootChordChanges.length > maxRows) {
    y += 5;
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(`... and ${rootChordChanges.length - maxRows} more chord changes`, x + 5, y);
    y += 5;
  }

  return y;
}

function formatTime(seconds) {
  /**
   * Format seconds as MM:SS
   */
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

function getNashvilleNumber(chord, key) {
  /**
   * Convert chord to Nashville Number System notation
   * Based on the key signature
   */

  // Parse chord to get root note
  let rootNote = extractRootNote(chord);

  // Parse key to get tonic
  let keyRoot = extractRootNote(key);

  // Determine if key is major or minor
  const isMinor = key.toLowerCase().includes('m') || key.toLowerCase().includes('minor');

  // Convert notes to semitones for calculation
  const noteToSemitone = {
    'C': 0, 'C#': 1, 'Db': 1, 'D': 2, 'D#': 3, 'Eb': 3, 'E': 4, 'F': 5,
    'F#': 6, 'Gb': 6, 'G': 7, 'G#': 8, 'Ab': 8, 'A': 9, 'A#': 10, 'Bb': 10, 'B': 11
  };

  const keySemitone = noteToSemitone[keyRoot] || 0;
  const chordSemitone = noteToSemitone[rootNote] || 0;

  // Calculate interval
  let interval = (chordSemitone - keySemitone + 12) % 12;

  // Map to Nashville numbers
  const majorNumbers = ['1', 'b2', '2', 'b3', '3', '4', 'b5', '5', 'b6', '6', 'b7', '7'];
  const minorNumbers = ['1', 'b2', 'b3', '3', '4', 'b5', '5', 'b6', '6', 'b7', '7', '7'];

  let number = isMinor ? minorNumbers[interval] : majorNumbers[interval];

  // Add chord quality indicators
  const chordLower = chord.toLowerCase();

  if (chordLower.includes('m') && !chordLower.includes('maj')) {
    // Minor chord
    number += 'm';
  }

  if (chordLower.includes('maj7')) {
    number += 'maj7';
  } else if (chordLower.includes('7')) {
    number += '7';
  }

  if (chordLower.includes('dim') || chordLower.includes('°')) {
    number += '°';
  }
  if (chordLower.includes('aug') || chordLower.includes('+')) {
    number += '+';
  }
  if (chordLower.includes('sus')) {
    number += 'sus';
  }

  return number;
}

async function updateJobStatus(jobId, status, progress, error = null) {
  const updateExpr = error
    ? 'SET #status = :status, progress = :progress, errorMessage = :error, updatedAt = :updated'
    : 'SET #status = :status, progress = :progress, updatedAt = :updated';

  const exprValues = {
    ':status': status,
    ':progress': progress,
    ':updated': new Date().toISOString()
  };

  if (error) {
    exprValues[':error'] = error;
  }

  await docClient.send(new UpdateCommand({
    TableName: JOBS_TABLE,
    Key: { jobId },
    UpdateExpression: updateExpr,
    ExpressionAttributeNames: { '#status': 'status' },
    ExpressionAttributeValues: exprValues
  }));
}

// AI-Powered Musical Analysis Functions
function separateIntoSyllables(word) {
  // Advanced syllable separation algorithm
  // Handles complex cases like "A-maz-ing", "beau-ti-ful", etc.
  
  const syllablePatterns = [
    // Common syllable patterns
    /([aeiou]+[^aeiou]*)/gi,
    // Handle consonant clusters
    /([^aeiou]*[aeiou]+)/gi
  ];
  
  // Simple implementation - can be enhanced with ML
  const syllables = [];
  let remaining = word.toLowerCase();
  
  // Handle common prefixes and suffixes
  const commonSyllables = {
    'amazing': ['A-', 'maz-', 'ing'],
    'grace': ['Grace'],
    'sweet': ['sweet'],
    'sound': ['sound'],
    'saved': ['saved'],
    'wretch': ['wretch'],
    'once': ['once'],
    'lost': ['lost'],
    'found': ['found'],
    'blind': ['blind']
  };
  
  if (commonSyllables[remaining]) {
    return commonSyllables[remaining];
  }
  
  // Fallback: return whole word
  return [word];
}

function identifyBeatsAndPickups(syllables, beatsPerMeasure) {
  // AI analysis to identify strong beats (downbeats) vs weak beats (pickups)
  // Based on musical stress patterns and syllable emphasis
  
  const downbeats = [];
  const pickups = [];
  
  // Simple heuristic: first syllable might be pickup, then regular beat pattern
  for (let i = 0; i < syllables.length; i++) {
    const syllable = syllables[i];
    
    // Check if this syllable falls on a strong beat
    const beatPosition = i % beatsPerMeasure;
    
    if (beatPosition === 0 && i > 0) {
      // This is likely a downbeat (except first syllable which might be pickup)
      downbeats.push({
        syllable,
        position: i,
        beatNumber: Math.floor(i / beatsPerMeasure) + 1
      });
    } else if (i === 0 && syllables.length > 1) {
      // First syllable might be pickup
      pickups.push({
        syllable,
        position: i,
        leadsTo: 1
      });
    } else {
      // Regular beat
      downbeats.push({
        syllable,
        position: i,
        beatNumber: Math.floor(i / beatsPerMeasure) + 1
      });
    }
  }
  
  return { downbeats, pickups };
}

function mapChordsToSyllables(syllables, chordsData) {
  // Map chord changes to specific syllables based on timing
  // Uses AI to determine which syllables get chord numbers
  
  if (!chordsData || !chordsData.chords) {
    return [];
  }
  
  const chordPositions = [];
  const chords = chordsData.chords;
  
  // Simple mapping: distribute chords across syllables
  const chordsPerSyllable = Math.max(1, Math.floor(syllables.length / chords.length));
  
  for (let i = 0; i < chords.length && i < syllables.length; i++) {
    const chord = chords[i];
    const syllableIndex = i * chordsPerSyllable;
    
    if (syllableIndex < syllables.length) {
      chordPositions.push({
        syllableIndex,
        chord: convertToNashvilleNumber(chord.chord, chordsData.key),
        isDownbeat: syllableIndex % 4 === 0, // Every 4th syllable is downbeat
        timing: chord.start
      });
    }
  }
  
  return chordPositions;
}

function convertToNashvilleNumber(chord, key) {
  // Convert chord names to Nashville numbers
  const nashvilleMap = {
    'C': '1', 'Dm': '2', 'Em': '3', 'F': '4', 'G': '5', 'Am': '6', 'Bdim': '7',
    'G': '1', 'Am': '2', 'Bm': '3', 'C': '4', 'D': '5', 'Em': '6', 'F#dim': '7',
    // Add more keys as needed
  };
  
  // Simple implementation - can be enhanced
  return nashvilleMap[chord] || '1';
}

function groupIntoMeasures(analysis, measuresPerLine) {
  // Group syllables and chords into measures (default 4 per line)
  const measureGroups = [];
  const syllablesPerMeasure = 4; // Assuming 4/4 time
  
  for (let i = 0; i < analysis.syllables.length; i += syllablesPerMeasure * measuresPerLine) {
    const group = {
      pickupNotes: analysis.pickupNotes.filter(p => 
        p.position >= i && p.position < i + syllablesPerMeasure * measuresPerLine
      ),
      downbeats: analysis.downbeats.filter(d => 
        d.position >= i && d.position < i + syllablesPerMeasure * measuresPerLine
      ).slice(0, measuresPerLine), // Max 4 measures per line
      downbeatChords: [],
      passingChords: []
    };
    
    // Map chords to downbeats and passing positions
    for (const chord of analysis.chordPositions) {
      if (chord.syllableIndex >= i && chord.syllableIndex < i + syllablesPerMeasure * measuresPerLine) {
        if (chord.isDownbeat) {
          group.downbeatChords.push({
            number: chord.chord,
            position: chord.syllableIndex - i
          });
        } else {
          group.passingChords.push({
            number: chord.chord,
            position: chord.syllableIndex - i + 20 + (chord.syllableIndex % 4) * 35 // Calculate position
          });
        }
      }
    }
    
    if (group.downbeats.length > 0 || group.pickupNotes.length > 0) {
      measureGroups.push(group);
    }
  }
  
  return measureGroups;
}